### PR TITLE
Fixes #418 - adds NOAA tides & currents

### LINKED ISSUE #418: Add NOAA Tides and Currents as a supporting layer
This layer is currently in OG FEV

### PR DESCRIPTION
**Pull request by 09Kathy**
Not sure what kind of icon to use (the one we're using in FEV doesn't really fit in with the others here). Nautical maps use a hallow circle, NOAA uses a stick pin thing, I could make it whatever color/shape we want. This is what I have for now: 
image

### CODE REVIEW

**Comment by lprivette** [comment]
I think we should go with the push pins actually. @HansVraga would there be any problem with us taking that symbol from NOAAs site and using it in DOI FEV?

**Comment by 09Kathy** [comment]
Would be the light blue ones on here:
image

**Comment by 09Kathy** [comment]
pins would look like this
image

**Comment by 09Kathy** [comment]
^ I'll fix that legend alignment if we're going with that

**Comment by HansVraga** [comment]
No issue that I can think of. Go for it - and if you want a cartographic review you can pull Gary and do a quick session. He really likes getting an opportunity to do that.

**Review by lprivette — APPROVED** [review]

**Pull request merged**
