### PR TITLE
Issue #78 - updates filter and geosearch

### PR DESCRIPTION
**Pull request by 09Kathy**

### CODE REVIEW

**Comment by lprivette** [comment]
Does this include the geosearch being reverted to normal? it shouldn't be highlighting any parks or buffers. We only want users to do that when first arriving at the site and then through the change filters modal.

The geosearch should just be a simple geosearch for finding a location

**Comment by 09Kathy** [comment]
I removed the buffers, but the popup with the name etc. still comes up if they search for a park/refuge - I'll remove that too

**Comment by 09Kathy** [comment]
Actually, the buffers are only removed from the search bar but still appear too - I'll remove all that!

**Comment by HansVraga** [comment]
Doesn't the pop-up appear for everything you geosearch for? We may want to keep it

**Comment by 09Kathy** [comment]
Yes. I can keep that!

**Comment by lprivette** [comment]
Let's also hide the Welcome text if users are opening that modal from the "Change Filters" button

**Comment by 09Kathy** [comment]
Although it works, there are massive sections copied and pasted - it seems like there should be a better way

**Pull request merged**
