### PR TITLE
fixed build issues; still seems to be an issue with esri-leaflet

### PR DESCRIPTION
**Pull request by lprivette**
Fixed the majority of the build issues. 

There's one remaining one and I think it's related to esri-leaflet. It's erroring when we we try to add the parks layer to the map.

### CODE REVIEW

**Comment by lprivette** [comment]
ah. it looks like the last merge some lines got lost telling the build scripts where to stop for the js bower_components. i'll fix and push it up and that should fix the pdfmake issue. 

At this point i'm not really worried about the Actions stuff. We want to make sure we can get a working app deployed and looking at the console errors it seems to be something with esri-leaflet

**Comment by lprivette** [comment]
hmmm looks like it didn't fix it in the actions. yeah idk whats wrong with it. I verified the file path and the pdfmake library is present.

**Comment by 09Kathy** [comment]
would that be a problem with the local build or just auto deploy? If we're more concerned with just getting the leaflet error to get it up manually, maybe that error's less important for the time being

**Comment by lprivette** [comment]
i think it's a problem with auto deploy.

pdfmake is working fine in the build I put on s3

**Comment by 09Kathy** [comment]
That's probably good! So does the test app work now?

**Comment by 09Kathy** [comment]
I just saw it! Nice work!!

**Pull request merged**
